// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.startupRolloutPrefs.geo.provider.use_gpsd", true);
user_pref("app.normandy.user_id", "2ef1b9d5-4a7f-4132-b32f-445a722ed944");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1567681719);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1567681839);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1567681285);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1567681479);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1567681405);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1567681599);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1567682079);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1567681959);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 717);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1567680797);
user_pref("browser.laterrun.bookkeeping.sessionCount", 6);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{a3f09456-16f6-4f44-a2ec-f109f28a6726}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1567612800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\",\"pinTab\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575458705650");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575460518650");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575458708945");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575462308945");
user_pref("browser.search.region", "CN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190902000000");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1567681449");
user_pref("browser.slowStartup.averageTime", 1331);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190902000000");
user_pref("browser.startup.homepage_override.mstone", "69.0");
user_pref("browser.startup.lastColdStartupCheck", 1575458703);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1567680803703");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.Manjaro.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "dbb7a41b5ea243a6a3ac6480b0b3f554");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Wed, 28 Aug 2019 19:55:12 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1567681721);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190902000000");
user_pref("extensions.lastAppVersion", "69.0");
user_pref("extensions.lastPlatformVersion", "69.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"3a1ecf42-6238-4282-8ca2-a99b17253863\",\"screenshots@mozilla.org\":\"ab4cdcdd-4b56-4ffc-a4fc-2965715c642e\",\"webcompat-reporter@mozilla.org\":\"6b81ea76-1259-425b-a2f3-be6c152293d6\",\"webcompat@mozilla.org\":\"f297ac40-dffe-4381-9d3c-6c3cee2845f2\",\"baidu-code-update@mozillaonline.com\":\"7be450d0-5cea-4c18-b94a-33c79a3644ae\",\"fxmonitor@mozilla.org\":\"89730d50-bb7d-4e32-9e07-fbfb309c6398\",\"default-theme@mozilla.org\":\"5e4c9a88-f6d4-4a14-93d1-5c62864e934a\",\"google@search.mozilla.org\":\"ef0b470a-64e3-47c5-98d3-800b711e58ae\",\"amazondotcom@search.mozilla.org\":\"929cab3f-c6df-4f0f-bc23-0a0eb9ace91c\",\"bing@search.mozilla.org\":\"5367575e-2c9a-4a35-b823-0f80261b38a6\",\"ddg@search.mozilla.org\":\"171df8d8-b9e5-4aec-b684-722acf90de77\",\"ebay@search.mozilla.org\":\"f46433ca-c969-49b2-8297-f113bf06e0fa\",\"twitter@search.mozilla.org\":\"12f0cab8-c9e7-4d1d-8ae3-59927d4daa05\",\"wikipedia@search.mozilla.org\":\"77b33f71-c8d7-49f9-8f7a-1ed125a55b2a\"}");
user_pref("idle.lastDailyNotification", 1567681747);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1567681596);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181212012434");
user_pref("media.gmp-manager.lastCheck", 1567681590);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1567681747);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "5f721b78-8752-4c16-99fa-3e4f9bbec304");
user_pref("security.sandbox.plugin.tempDirSuffix", "0690beec-d351-46ad-b292-6a55da411893");
user_pref("services.blocklist.addons.checked", 1567681758);
user_pref("services.blocklist.gfx.checked", 1567681886);
user_pref("services.blocklist.onecrl.checked", 1567681758);
user_pref("services.blocklist.pinning.checked", 1567681886);
user_pref("services.blocklist.plugins.checked", 1567681758);
user_pref("services.settings.clock_skew_seconds", 39602);
user_pref("services.settings.last_etag", "\"1567621920756\"");
user_pref("services.settings.last_update_seconds", 1575419103);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1567750762);
user_pref("services.settings.main.language-dictionaries.last_check", 1567681758);
user_pref("services.settings.main.normandy-recipes.last_check", 1567750762);
user_pref("services.settings.main.sites-classification.last_check", 1567681758);
user_pref("services.settings.main.tippytop.last_check", 1567681758);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1567681747);
user_pref("toolkit.startup.last_success", 1567832027);
user_pref("toolkit.telemetry.cachedClientID", "521af8bb-4cd4-492e-9996-31b63133b009");
user_pref("toolkit.telemetry.previousBuildID", "20190902000000");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
